# TCL File Generated by Component Editor 9.0
# Wed Jul 17 21:25:24 CST 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | seg7_lut_8 "SEG7_LUT_8" v1.0.1
# | null 2013.07.17.21:25:24
# | 
# | 
# | F:/DigitalDesignCourse/LED/ip/SEG7_LUT_8/hdl/SEG7_LUT_8.v
# | 
# |    ./hdl/SEG7_LUT.v syn, sim
# |    ./hdl/SEG7_LUT_8.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module seg7_lut_8
# | 
set_module_property NAME seg7_lut_8
set_module_property VERSION 1.0.1
set_module_property INTERNAL false
set_module_property GROUP "Terasic Technologies Inc"
set_module_property DISPLAY_NAME SEG7_LUT_8
set_module_property TOP_LEVEL_HDL_FILE hdl/SEG7_LUT_8.v
set_module_property TOP_LEVEL_HDL_MODULE SEG7_LUT_8
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/SEG7_LUT.v {SYNTHESIS SIMULATION}
add_file hdl/SEG7_LUT_8.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk ptfSchematicName ""

set_interface_property clk ENABLED true

add_interface_port clk iCLK clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ASSOCIATED_CLOCK clk
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave iWR write Input 1
add_interface_port avalon_slave iDIG writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end oSEG0 export Output 7
add_interface_port conduit_end oSEG1 export Output 7
add_interface_port conduit_end oSEG2 export Output 7
add_interface_port conduit_end oSEG3 export Output 7
add_interface_port conduit_end oSEG4 export Output 7
add_interface_port conduit_end oSEG5 export Output 7
add_interface_port conduit_end oSEG6 export Output 7
add_interface_port conduit_end oSEG7 export Output 7
# | 
# +-----------------------------------
