  //Example instantiation for system 'kernel'
  kernel kernel_inst
    (
      .LCD_E_from_the_lcd_0                      (LCD_E_from_the_lcd_0),
      .LCD_RS_from_the_lcd_0                     (LCD_RS_from_the_lcd_0),
      .LCD_RW_from_the_lcd_0                     (LCD_RW_from_the_lcd_0),
      .LCD_data_to_and_from_the_lcd_0            (LCD_data_to_and_from_the_lcd_0),
      .SRAM_ADDR_from_the_sram_16bit_512k_0      (SRAM_ADDR_from_the_sram_16bit_512k_0),
      .SRAM_CE_N_from_the_sram_16bit_512k_0      (SRAM_CE_N_from_the_sram_16bit_512k_0),
      .SRAM_DQ_to_and_from_the_sram_16bit_512k_0 (SRAM_DQ_to_and_from_the_sram_16bit_512k_0),
      .SRAM_LB_N_from_the_sram_16bit_512k_0      (SRAM_LB_N_from_the_sram_16bit_512k_0),
      .SRAM_OE_N_from_the_sram_16bit_512k_0      (SRAM_OE_N_from_the_sram_16bit_512k_0),
      .SRAM_UB_N_from_the_sram_16bit_512k_0      (SRAM_UB_N_from_the_sram_16bit_512k_0),
      .SRAM_WE_N_from_the_sram_16bit_512k_0      (SRAM_WE_N_from_the_sram_16bit_512k_0),
      .VGA_BLANK_from_the_vga_0                  (VGA_BLANK_from_the_vga_0),
      .VGA_B_from_the_vga_0                      (VGA_B_from_the_vga_0),
      .VGA_CLK_from_the_vga_0                    (VGA_CLK_from_the_vga_0),
      .VGA_G_from_the_vga_0                      (VGA_G_from_the_vga_0),
      .VGA_HS_from_the_vga_0                     (VGA_HS_from_the_vga_0),
      .VGA_R_from_the_vga_0                      (VGA_R_from_the_vga_0),
      .VGA_SYNC_from_the_vga_0                   (VGA_SYNC_from_the_vga_0),
      .VGA_VS_from_the_vga_0                     (VGA_VS_from_the_vga_0),
      .areset_to_the_pll                         (areset_to_the_pll),
      .clk_50                                    (clk_50),
      .iCLK_25_to_the_vga_0                      (iCLK_25_to_the_vga_0),
      .in_port_to_the_gpio                       (in_port_to_the_gpio),
      .in_port_to_the_hardmodle                  (in_port_to_the_hardmodle),
      .in_port_to_the_key                        (in_port_to_the_key),
      .locked_from_the_pll                       (locked_from_the_pll),
      .phasedone_from_the_pll                    (phasedone_from_the_pll),
      .pll_c0_out                                (pll_c0_out),
      .reset_n                                   (reset_n),
      .select_n_to_the_cfi_flash                 (select_n_to_the_cfi_flash),
      .tri_state_bridge_address                  (tri_state_bridge_address),
      .tri_state_bridge_data                     (tri_state_bridge_data),
      .tri_state_bridge_readn                    (tri_state_bridge_readn),
      .write_n_to_the_cfi_flash                  (write_n_to_the_cfi_flash)
    );

